/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as UsernameRouteImport } from './routes/$username'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DiscoverRouteImport } from './routes/discover'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as StartRouteImport } from './routes/start'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AdminCommentsRouteImport } from './routes/admin_.comments'
import { Route as AdminProjectsRouteImport } from './routes/admin_.projects'
import { Route as AdminUsersRouteImport } from './routes/admin_.users'
import { Route as ApiBeehiivSubscribeRouteImport } from './routes/api/beehiiv-subscribe'
import { Route as AuthIndexRouteImport } from './routes/auth/index'
import { Route as AuthCallbackRouteImport } from './routes/auth/callback'
import { Route as ProjectsSlugRouteImport } from './routes/projects.$slug'
import { Route as ProjectsSlugEditRouteImport } from './routes/projects_.$slug.edit'
import { Route as ProjectsSlugUpdatesUpdateIdRouteImport } from './routes/projects.$slug.updates.$updateId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const UsernameRoute = UsernameRouteImport.update({
  id: '/$username',
  path: '/$username',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DiscoverRoute = DiscoverRouteImport.update({
  id: '/discover',
  path: '/discover',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const StartRoute = StartRouteImport.update({
  id: '/start',
  path: '/start',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminCommentsRoute = AdminCommentsRouteImport.update({
  id: '/admin_/comments',
  path: '/admin/comments',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/admin_/projects',
  path: '/admin/projects',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin_/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiBeehiivSubscribeRoute = ApiBeehiivSubscribeRouteImport.update({
  id: '/api/beehiiv-subscribe',
  path: '/api/beehiiv-subscribe',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/auth/',
  path: '/auth/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthCallbackRoute = AuthCallbackRouteImport.update({
  id: '/auth/callback',
  path: '/auth/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugRoute = ProjectsSlugRouteImport.update({
  id: '/projects/$slug',
  path: '/projects/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugEditRoute = ProjectsSlugEditRouteImport.update({
  id: '/projects_/$slug/edit',
  path: '/projects/$slug/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjectsSlugUpdatesUpdateIdRoute =
  ProjectsSlugUpdatesUpdateIdRouteImport.update({
    id: '/updates/$updateId',
    path: '/updates/$updateId',
    getParentRoute: () => ProjectsSlugRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/beehiiv-subscribe': typeof ApiBeehiivSubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/projects/$slug/edit': typeof ProjectsSlugEditRoute
  '/projects/$slug/updates/$updateId': typeof ProjectsSlugUpdatesUpdateIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/admin/comments': typeof AdminCommentsRoute
  '/admin/projects': typeof AdminProjectsRoute
  '/admin/users': typeof AdminUsersRoute
  '/api/beehiiv-subscribe': typeof ApiBeehiivSubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/auth': typeof AuthIndexRoute
  '/projects/$slug/edit': typeof ProjectsSlugEditRoute
  '/projects/$slug/updates/$updateId': typeof ProjectsSlugUpdatesUpdateIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/$username': typeof UsernameRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/dashboard': typeof DashboardRoute
  '/discover': typeof DiscoverRoute
  '/faq': typeof FaqRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/settings': typeof SettingsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/start': typeof StartRoute
  '/terms': typeof TermsRoute
  '/admin_/comments': typeof AdminCommentsRoute
  '/admin_/projects': typeof AdminProjectsRoute
  '/admin_/users': typeof AdminUsersRoute
  '/api/beehiiv-subscribe': typeof ApiBeehiivSubscribeRoute
  '/auth/callback': typeof AuthCallbackRoute
  '/projects/$slug': typeof ProjectsSlugRouteWithChildren
  '/auth/': typeof AuthIndexRoute
  '/projects_/$slug/edit': typeof ProjectsSlugEditRoute
  '/projects/$slug/updates/$updateId': typeof ProjectsSlugUpdatesUpdateIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/$username'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/discover'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/sitemap.xml'
    | '/start'
    | '/terms'
    | '/admin/comments'
    | '/admin/projects'
    | '/admin/users'
    | '/api/beehiiv-subscribe'
    | '/auth/callback'
    | '/projects/$slug'
    | '/auth/'
    | '/projects/$slug/edit'
    | '/projects/$slug/updates/$updateId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/$username'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/discover'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/sitemap.xml'
    | '/start'
    | '/terms'
    | '/admin/comments'
    | '/admin/projects'
    | '/admin/users'
    | '/api/beehiiv-subscribe'
    | '/auth/callback'
    | '/projects/$slug'
    | '/auth'
    | '/projects/$slug/edit'
    | '/projects/$slug/updates/$updateId'
  id:
    | '__root__'
    | '/'
    | '/$username'
    | '/about'
    | '/admin'
    | '/contact'
    | '/dashboard'
    | '/discover'
    | '/faq'
    | '/pricing'
    | '/privacy'
    | '/settings'
    | '/sitemap.xml'
    | '/start'
    | '/terms'
    | '/admin_/comments'
    | '/admin_/projects'
    | '/admin_/users'
    | '/api/beehiiv-subscribe'
    | '/auth/callback'
    | '/projects/$slug'
    | '/auth/'
    | '/projects_/$slug/edit'
    | '/projects/$slug/updates/$updateId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  UsernameRoute: typeof UsernameRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  ContactRoute: typeof ContactRoute
  DashboardRoute: typeof DashboardRoute
  DiscoverRoute: typeof DiscoverRoute
  FaqRoute: typeof FaqRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  SettingsRoute: typeof SettingsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StartRoute: typeof StartRoute
  TermsRoute: typeof TermsRoute
  AdminCommentsRoute: typeof AdminCommentsRoute
  AdminProjectsRoute: typeof AdminProjectsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  ApiBeehiivSubscribeRoute: typeof ApiBeehiivSubscribeRoute
  AuthCallbackRoute: typeof AuthCallbackRoute
  ProjectsSlugRoute: typeof ProjectsSlugRouteWithChildren
  AuthIndexRoute: typeof AuthIndexRoute
  ProjectsSlugEditRoute: typeof ProjectsSlugEditRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$username': {
      id: '/$username'
      path: '/$username'
      fullPath: '/$username'
      preLoaderRoute: typeof UsernameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/discover': {
      id: '/discover'
      path: '/discover'
      fullPath: '/discover'
      preLoaderRoute: typeof DiscoverRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/start': {
      id: '/start'
      path: '/start'
      fullPath: '/start'
      preLoaderRoute: typeof StartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/comments': {
      id: '/admin_/comments'
      path: '/admin/comments'
      fullPath: '/admin/comments'
      preLoaderRoute: typeof AdminCommentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/projects': {
      id: '/admin_/projects'
      path: '/admin/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin_/users': {
      id: '/admin_/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/beehiiv-subscribe': {
      id: '/api/beehiiv-subscribe'
      path: '/api/beehiiv-subscribe'
      fullPath: '/api/beehiiv-subscribe'
      preLoaderRoute: typeof ApiBeehiivSubscribeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/': {
      id: '/auth/'
      path: '/auth'
      fullPath: '/auth/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/callback': {
      id: '/auth/callback'
      path: '/auth/callback'
      fullPath: '/auth/callback'
      preLoaderRoute: typeof AuthCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug': {
      id: '/projects/$slug'
      path: '/projects/$slug'
      fullPath: '/projects/$slug'
      preLoaderRoute: typeof ProjectsSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects_/$slug/edit': {
      id: '/projects_/$slug/edit'
      path: '/projects/$slug/edit'
      fullPath: '/projects/$slug/edit'
      preLoaderRoute: typeof ProjectsSlugEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projects/$slug/updates/$updateId': {
      id: '/projects/$slug/updates/$updateId'
      path: '/updates/$updateId'
      fullPath: '/projects/$slug/updates/$updateId'
      preLoaderRoute: typeof ProjectsSlugUpdatesUpdateIdRouteImport
      parentRoute: typeof ProjectsSlugRoute
    }
  }
}

interface ProjectsSlugRouteChildren {
  ProjectsSlugUpdatesUpdateIdRoute: typeof ProjectsSlugUpdatesUpdateIdRoute
}

const ProjectsSlugRouteChildren: ProjectsSlugRouteChildren = {
  ProjectsSlugUpdatesUpdateIdRoute: ProjectsSlugUpdatesUpdateIdRoute,
}

const ProjectsSlugRouteWithChildren = ProjectsSlugRoute._addFileChildren(
  ProjectsSlugRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  UsernameRoute: UsernameRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  ContactRoute: ContactRoute,
  DashboardRoute: DashboardRoute,
  DiscoverRoute: DiscoverRoute,
  FaqRoute: FaqRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  SettingsRoute: SettingsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StartRoute: StartRoute,
  TermsRoute: TermsRoute,
  AdminCommentsRoute: AdminCommentsRoute,
  AdminProjectsRoute: AdminProjectsRoute,
  AdminUsersRoute: AdminUsersRoute,
  ApiBeehiivSubscribeRoute: ApiBeehiivSubscribeRoute,
  AuthCallbackRoute: AuthCallbackRoute,
  ProjectsSlugRoute: ProjectsSlugRouteWithChildren,
  AuthIndexRoute: AuthIndexRoute,
  ProjectsSlugEditRoute: ProjectsSlugEditRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
